// <auto-generated />
namespace DataAccessLayerr.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class datanull : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(datanull));
        
        string IMigrationMetadata.Id
        {
            get { return "202203182033339_datanull"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
